packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  next: ~16.1.6
  react: ^19.0.0
  react-dom: ^19.0.0
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  less: true
  nx: true
  sharp: true
  unrs-resolver: true
