import { Tree, createProjectGraphAsync, joinPathFragments } from '@nx/devkit';
import {
  SyncError,
  type SyncGeneratorResult,
} from 'nx/src/utils/sync-generators';

import * as yaml from 'yaml';

const DEFAULT_NAMESPACE = 'default';

// namespace values become file names (skaffold/<namespace>.yaml) and are
// used as-is in kubectl operations, so they must be safe on both fronts
const NAMESPACE_PATTERN = /^[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?$/;

// these names are already claimed by hand-maintained top-level files
const RESERVED_NAMESPACES = new Set(['infra', 'skaffold']);

// the project name is used as-is as the Docker image name
const IMAGE_NAME_PATTERN = /^[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*$/;

// prepended to every generated file so stale ones (e.g. a namespace that no
// app references anymore) can be safely identified and pruned later, without
// ever touching a file a developer authored by hand
const GENERATED_FILE_MARKER =
  '# Generated by @dxs/skaffold:sync. Do not edit directly — run `nx sync` to regenerate.\n';

type App = { name: string; data: { root: string } };
type K8sResource = {
  file: string;
  resource: {
    kind?: string;
    metadata?: { name?: string; namespace?: string };
    spec?: { ports?: { port?: unknown }[] };
  };
};

function isYamlFile(file: string): boolean {
  return file.endsWith('.yaml') || file.endsWith('.yml');
}

function hasYamlFiles(tree: Tree, dir: string): boolean {
  return tree.children(dir).some(isYamlFile);
}

function assertValidImageName(appName: string): void {
  if (!IMAGE_NAME_PATTERN.test(appName)) {
    throw new SyncError(
      `Project "${appName}" is not a valid Docker image name`,
      [
        `Docker image names must be lowercase alphanumeric characters, optionally`,
        `separated by single '.', '_', '__', or one-or-more '-'.`,
        `The project's name is used directly as its built image's name, so rename the project.`,
      ],
    );
  }
}

function getDevTarget(tree: Tree, dockerfilePath: string): string | undefined {
  const content = tree.read(dockerfilePath, 'utf-8') ?? '';
  return /^FROM\s+.+\s+AS\s+dev\s*$/im.test(content) ? 'dev' : undefined;
}

function buildArtifact(app: App, target?: string) {
  return {
    image: app.name,
    // relative to this file's own directory (skaffold/), since this config
    // is always loaded as a `requires` module, never as the entrypoint
    context: '..',
    docker: {
      dockerfile: `${app.data.root}/Dockerfile`,
      ...(target ? { target } : {}),
    },
    sync: {
      manual: [
        { src: `${app.data.root}/src/**/*`, dest: '.' },
        { src: `${app.data.root}/public/**/*`, dest: '.' },
      ],
    },
  };
}

function buildProductionArtifact(app: App) {
  return {
    image: app.name,
    context: '..',
    docker: {
      dockerfile: `${app.data.root}/Dockerfile`,
      // no target: builds the Dockerfile's last stage (the real production build)
    },
    // no sync: nothing in a production image is watching for file changes
  };
}

function readK8sResources(tree: Tree, k8sDir: string): K8sResource[] {
  const resources: K8sResource[] = [];

  for (const file of tree.children(k8sDir)) {
    if (!isYamlFile(file)) {
      continue;
    }

    const filePath = joinPathFragments(k8sDir, file);
    const content = tree.read(filePath, 'utf-8');
    if (!content) {
      continue;
    }

    for (const doc of yaml.parseAllDocuments(content)) {
      if (doc.errors.length > 0) {
        throw new SyncError(`Failed to parse ${filePath}`, [
          ...doc.errors.map((error) => error.message),
        ]);
      }

      const resource = doc.toJSON();
      // skip empty documents, e.g. from a trailing "---"
      if (resource) {
        resources.push({ file: filePath, resource });
      }
    }
  }

  return resources;
}

function getResourceNamespaces(tree: Tree, k8sDir: string): string[] {
  return readK8sResources(tree, k8sDir)
    .map(({ resource }) => resource.metadata?.namespace)
    .filter((namespace): namespace is string => Boolean(namespace));
}

function getAppNamespace(tree: Tree, k8sDir: string, appName: string): string {
  const namespaces = new Set(getResourceNamespaces(tree, k8sDir));

  if (namespaces.size > 1) {
    throw new SyncError(`App "${appName}" declares more than one namespace`, [
      `Found namespaces: ${[...namespaces].join(', ')} across resources in ${k8sDir}.`,
      `Each app must target exactly one namespace across all of its k8s manifests.`,
    ]);
  }

  const namespace =
    namespaces.size === 1 ? [...namespaces][0] : DEFAULT_NAMESPACE;

  if (namespace !== DEFAULT_NAMESPACE && !NAMESPACE_PATTERN.test(namespace)) {
    throw new SyncError(
      `App "${appName}" declares an invalid namespace "${namespace}"`,
      [
        `Kubernetes namespace names must be lowercase alphanumeric characters or '-',`,
        `must start and end with an alphanumeric character, and be at most 63 characters long.`,
        `Found in ${k8sDir}.`,
      ],
    );
  }

  if (RESERVED_NAMESPACES.has(namespace)) {
    throw new SyncError(
      `App "${appName}" cannot use the reserved namespace "${namespace}"`,
      [
        `"${namespace}" is reserved for the hand-maintained skaffold/${namespace}.yaml.`,
        `Choose a different namespace for this app.`,
      ],
    );
  }

  return namespace;
}

function getServicePortForwards(tree: Tree, k8sDir: string, namespace: string) {
  const portForwards: {
    resourceType: string;
    resourceName: string;
    namespace: string;
    port: number;
    localPort: number;
  }[] = [];

  for (const { file, resource } of readK8sResources(tree, k8sDir)) {
    if (resource.kind !== 'Service') {
      continue;
    }

    const resourceName = resource.metadata?.name;
    if (!resourceName) {
      throw new SyncError(`Service in ${file} is missing metadata.name`, [
        `Every Service manifest must declare metadata.name so it can be port-forwarded.`,
      ]);
    }

    for (const port of resource.spec?.ports ?? []) {
      if (typeof port.port !== 'number') {
        throw new SyncError(
          `Service "${resourceName}" in ${file} has a port entry without a numeric "port"`,
          [`Found: ${JSON.stringify(port)}`],
        );
      }

      portForwards.push({
        resourceType: 'service',
        resourceName,
        namespace,
        port: port.port,
        localPort: port.port,
      });
    }
  }

  return portForwards;
}

function buildNamespaceManifest(namespace: string) {
  if (namespace === DEFAULT_NAMESPACE) {
    // the "default" namespace always exists; every other namespace referenced
    // by deploy.kubectl.defaultNamespace must be created before it's deployed into
    return undefined;
  }

  return {
    path: `${namespace}-namespace.yaml`,
    content: yaml.stringify({
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: { name: namespace },
    }),
  };
}

function buildNamespaceConfig(tree: Tree, namespace: string, apps: App[]) {
  const portForward = apps.flatMap((app) =>
    getServicePortForwards(
      tree,
      joinPathFragments(app.data.root, 'k8s'),
      namespace,
    ),
  );

  const namespaceManifest = buildNamespaceManifest(namespace);

  return {
    apiVersion: 'skaffold/v4beta13',
    kind: 'Config',
    metadata: {
      name: `dx-stack-${namespace}`,
    },
    build: {
      artifacts: apps.map((app) =>
        buildArtifact(
          app,
          getDevTarget(tree, joinPathFragments(app.data.root, 'Dockerfile')),
        ),
      ),
      local: {
        useDockerCLI: true,
        useBuildkit: true,
      },
    },
    manifests: {
      // relative to this file's own directory (skaffold/), since this config
      // is always loaded as a `requires` module, never as the entrypoint
      rawYaml: [
        ...(namespaceManifest ? [namespaceManifest.path] : []),
        ...apps.map((app) => `../${app.data.root}/k8s/*.yaml`),
      ],
    },
    deploy: {
      kubectl: {
        defaultNamespace: namespace,
        flags: {
          global: ['--context=minikube'],
        },
      },
    },
    ...(portForward.length > 0 ? { portForward } : {}),
    // activated with `-p production`; skaffold propagates an activated
    // profile name to every required config that defines a matching one, so
    // `-p production` on the top-level skaffold.yaml reaches this file too
    profiles: [
      {
        name: 'production',
        build: {
          artifacts: apps.map((app) => buildProductionArtifact(app)),
          local: {
            useDockerCLI: true,
            useBuildkit: true,
          },
        },
      },
    ],
  };
}

export async function syncGenerator(tree: Tree): Promise<SyncGeneratorResult> {
  const graph = await createProjectGraphAsync();

  const apps: App[] = Object.values(graph.nodes)
    .filter((node) => {
      const k8sDir = joinPathFragments(node.data.root, 'k8s');
      return (
        node.type === 'app' &&
        tree.exists(joinPathFragments(node.data.root, 'Dockerfile')) &&
        tree.exists(k8sDir) &&
        hasYamlFiles(tree, k8sDir)
      );
    })
    // deterministic order so regenerating with no actual changes produces
    // byte-identical output, regardless of project graph iteration order
    .sort((a, b) => a.name.localeCompare(b.name));

  for (const app of apps) {
    assertValidImageName(app.name);
  }

  const appsByNamespace = new Map<string, App[]>();
  for (const app of apps) {
    const namespace = getAppNamespace(
      tree,
      joinPathFragments(app.data.root, 'k8s'),
      app.name,
    );
    appsByNamespace.set(namespace, [
      ...(appsByNamespace.get(namespace) ?? []),
      app,
    ]);
  }

  const namespaces = [...appsByNamespace.keys()].sort();

  const expectedFiles = new Set<string>(['skaffold.yaml']);
  for (const namespace of namespaces) {
    expectedFiles.add(`${namespace}.yaml`);
    if (namespace !== DEFAULT_NAMESPACE) {
      expectedFiles.add(`${namespace}-namespace.yaml`);
    }
  }

  // remove generated files left behind by a previous run that are no longer
  // needed (e.g. an app switched namespaces); never touches hand-authored
  // files, since only files carrying our own marker comment are eligible
  for (const file of tree.children('skaffold')) {
    if (expectedFiles.has(file) || file === 'infra.yaml') {
      continue;
    }
    if (!isYamlFile(file)) {
      continue;
    }

    const filePath = `skaffold/${file}`;
    const content = tree.read(filePath, 'utf-8');
    if (content?.startsWith(GENERATED_FILE_MARKER)) {
      tree.delete(filePath);
    }
  }

  const written = new Set<string>();
  function write(path: string, content: string) {
    if (written.has(path)) {
      throw new SyncError(
        `Generated file "${path}" would be written more than once`,
        [`Two different namespaces produced a colliding generated file name.`],
      );
    }
    written.add(path);
    tree.write(path, GENERATED_FILE_MARKER + content);
  }

  for (const namespace of namespaces) {
    const namespaceApps = appsByNamespace.get(namespace) ?? [];

    const namespaceManifest = buildNamespaceManifest(namespace);
    if (namespaceManifest) {
      write(`skaffold/${namespaceManifest.path}`, namespaceManifest.content);
    }

    write(
      `skaffold/${namespace}.yaml`,
      yaml.stringify(buildNamespaceConfig(tree, namespace, namespaceApps)),
    );
  }

  write(
    'skaffold/skaffold.yaml',
    yaml.stringify({
      apiVersion: 'skaffold/v4beta13',
      kind: 'Config',
      metadata: {
        name: 'dx-stack',
      },
      requires: [
        { path: 'infra.yaml' },
        ...namespaces.map((namespace) => ({ path: `${namespace}.yaml` })),
      ],
    }),
  );

  return {
    outOfSyncMessage: 'skaffold/skaffold.yaml is missing or not in sync',
  };
}

export default syncGenerator;
