import { buildNestJsDockerfile } from './dockerfile';

describe('buildNestJsDockerfile', () => {
  it('generates a Dockerfile with the expected stages', () => {
    const dockerfile = buildNestJsDockerfile(
      { name: 'svc', root: 'apps/svc' },
      [],
    );

    expect(dockerfile).toContain('FROM node:24-alpine AS base');
    expect(dockerfile).toContain('FROM base AS deps');
    expect(dockerfile).toContain('FROM deps AS source');
    expect(dockerfile).toContain('FROM source AS builder');
    expect(dockerfile).toContain('FROM source AS dev');
    expect(dockerfile).toContain('FROM base AS runner');
    expect(dockerfile).toContain(
      'COPY apps/svc/package.json apps/svc/package.json',
    );
    expect(dockerfile).toContain('COPY apps/svc apps/svc');
    expect(dockerfile).toContain('nx run svc:prune --skip-sync');
    expect(dockerfile).toContain('"nx", "serve", "svc", "--skip-sync"');
    expect(dockerfile).toContain('pnpm install --prod --frozen-lockfile');
  });

  it('places the marker comment after the syntax directive, never before it', () => {
    const lines = buildNestJsDockerfile(
      { name: 'svc', root: 'apps/svc' },
      [],
    ).split('\n');

    expect(lines[0]).toBe('# syntax=docker/dockerfile:1');
    expect(lines[1]).toContain('Generated by @dx-stack/skaffold:sync');
  });

  it('copies package.json and source for each workspace dependency', () => {
    const dockerfile = buildNestJsDockerfile(
      { name: 'svc', root: 'apps/svc' },
      [{ name: 'shared-lib', root: 'packages/shared-lib' }],
    );

    expect(dockerfile).toContain(
      'COPY packages/shared-lib/package.json packages/shared-lib/package.json',
    );
    expect(dockerfile).toContain(
      'COPY packages/shared-lib packages/shared-lib',
    );
  });

  it('mirrors the local monorepo layout under /workspace in the container', () => {
    const dockerfile = buildNestJsDockerfile(
      { name: 'svc', root: 'apps/svc' },
      [],
    );

    expect(dockerfile).toContain('WORKDIR /workspace');
    expect(dockerfile).toContain('WORKDIR /workspace/apps/svc/dist');
    expect(dockerfile).toContain(
      'COPY --from=builder --chown=nestjs:nodejs /workspace/apps/svc/dist ./',
    );
    expect(dockerfile).toContain('CMD ["node", "main.js"]');
  });
});
