import { buildNextJsDockerfile } from './dockerfile';

describe('buildNextJsDockerfile', () => {
  it('generates a Dockerfile with the expected stages', () => {
    const dockerfile = buildNextJsDockerfile(
      { name: 'demo', root: 'apps/demo' },
      [],
      'apps/demo/.next',
    );

    expect(dockerfile).toContain('FROM node:24-alpine AS base');
    expect(dockerfile).toContain('FROM base AS deps');
    expect(dockerfile).toContain('FROM deps AS source');
    expect(dockerfile).toContain('FROM source AS builder');
    expect(dockerfile).toContain('FROM source AS dev');
    expect(dockerfile).toContain('FROM base AS runner');
    expect(dockerfile).toContain(
      'COPY apps/demo/package.json apps/demo/package.json',
    );
    expect(dockerfile).toContain('COPY apps/demo apps/demo');
    expect(dockerfile).toContain('nx build demo --skip-sync');
    expect(dockerfile).toContain('"nx", "dev", "demo", "--skip-sync"');
    expect(dockerfile).toContain('ENV HOSTNAME="0.0.0.0"');
    expect(dockerfile).toContain('ENV NEXT_TELEMETRY_DISABLED=1');
    expect(dockerfile).toContain(
      '--mount=type=cache,id=next-demo,target=/workspace/apps/demo/.next/cache',
    );
  });

  it('places the marker comment after the syntax directive, never before it', () => {
    const lines = buildNextJsDockerfile(
      { name: 'demo', root: 'apps/demo' },
      [],
      'apps/demo/.next',
    ).split('\n');

    expect(lines[0]).toBe('# syntax=docker/dockerfile:1');
    expect(lines[1]).toContain('Generated by @dx-stack/skaffold:sync');
  });

  it('copies package.json and source for each workspace dependency', () => {
    const dockerfile = buildNextJsDockerfile(
      { name: 'demo', root: 'apps/demo' },
      [{ name: 'shared-ui', root: 'packages/shared-ui' }],
      'apps/demo/.next',
    );

    expect(dockerfile).toContain(
      'COPY packages/shared-ui/package.json packages/shared-ui/package.json',
    );
    expect(dockerfile).toContain('COPY packages/shared-ui packages/shared-ui');
  });

  it('mirrors the local monorepo layout under /workspace in the container', () => {
    const dockerfile = buildNextJsDockerfile(
      { name: 'demo', root: 'apps/demo' },
      [],
      'apps/demo/.next',
    );

    expect(dockerfile).toContain('WORKDIR /workspace');
    expect(dockerfile).toContain(
      'COPY --from=builder --chown=nextjs:nodejs /workspace/apps/demo/.next/standalone ./',
    );
  });

  it('respects a custom build output directory, not just ".next"', () => {
    const dockerfile = buildNextJsDockerfile(
      { name: 'demo', root: 'apps/demo' },
      [],
      'apps/demo/build',
    );

    expect(dockerfile).toContain(
      '--mount=type=cache,id=next-demo,target=/workspace/apps/demo/build/cache',
    );
    expect(dockerfile).toContain(
      'COPY --from=builder --chown=nextjs:nodejs /workspace/apps/demo/build/standalone ./',
    );
    expect(dockerfile).toContain(
      'COPY --from=builder --chown=nextjs:nodejs /workspace/apps/demo/build/static ./apps/demo/build/static',
    );
    expect(dockerfile).not.toContain('.next');
  });
});
