apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: apps
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: demo
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: HOSTNAME
              value: '0.0.0.0'
