import {
  Tree,
  createProjectGraphAsync,
  joinPathFragments,
  workspaceRoot,
} from '@nx/devkit';
import {
  SyncError,
  type SyncGeneratorResult,
} from 'nx/src/utils/sync-generators';

import { join, relative, sep } from 'path';
import * as ts from 'typescript';
import * as yaml from 'yaml';

const DEFAULT_NAMESPACE = 'default';

// namespace values become file names (skaffold/<namespace>.yaml) and are
// used as-is in kubectl operations, so they must be safe on both fronts
const NAMESPACE_PATTERN = /^[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?$/;

// these names are already claimed by hand-maintained top-level files
const RESERVED_NAMESPACES = new Set(['infra', 'skaffold']);

// the project name is used as-is as the Docker image name
const IMAGE_NAME_PATTERN = /^[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*$/;

// present (anywhere) in every generated file so stale ones (e.g. a namespace
// that no app references anymore) can be safely identified and pruned later,
// without ever touching a file a developer authored by hand
const GENERATED_FILE_MARKER =
  '# Generated by @dxs/next-skaffold:sync. Do not edit directly — run `nx sync` to regenerate.\n';

// WORKDIR for the generated Next.js Dockerfile, so the container mirrors the
// local monorepo layout beneath it (e.g. /workspace/apps/demo/...) rather
// than nesting it under a same-ish-looking "app" directory (confusable with
// the local "apps/" one). Deliberately not the container's filesystem root:
// Nx's own workspace-root detection breaks there (it special-cases hitting
// "/" while walking up looking for nx.json), and even forcing it via
// NX_WORKSPACE_ROOT_PATH=/ makes the Nx daemon hang calculating the project
// graph across the whole container filesystem (/proc, /sys, etc. included).
const WORKSPACE_DIR = '/workspace';

type App = { name: string; data: { root: string } };
type ProjectGraph = Awaited<ReturnType<typeof createProjectGraphAsync>>;
type K8sResource = {
  file: string;
  resource: {
    kind?: string;
    metadata?: { name?: string; namespace?: string };
    spec?: { ports?: { port?: unknown }[] };
  };
};

function isYamlFile(file: string): boolean {
  return file.endsWith('.yaml') || file.endsWith('.yml');
}

function hasYamlFiles(tree: Tree, dir: string): boolean {
  return tree.children(dir).some(isYamlFile);
}

function assertValidImageName(appName: string): void {
  if (!IMAGE_NAME_PATTERN.test(appName)) {
    throw new SyncError(
      `Project "${appName}" is not a valid Docker image name`,
      [
        `Docker image names must be lowercase alphanumeric characters, optionally`,
        `separated by single '.', '_', '__', or one-or-more '-'.`,
        `The project's name is used directly as its built image's name, so rename the project.`,
      ],
    );
  }
}

// the only framework this generator knows how to *generate* a Dockerfile
// for so far. Adding a new one means: add its detection dependency below,
// write a buildXyzDockerfile() alongside buildNextJsDockerfile(), and add a
// case to buildDockerfile()'s dispatch. Anything else falls back to
// requiring a hand-written Dockerfile — see detectFramework() below.
type Framework = 'nextjs';

// dependency (in the app's own package.json) that identifies each framework
const FRAMEWORK_DEPENDENCY: Record<Framework, string> = {
  nextjs: 'next',
};

// step 1: analyse the project and identify its framework. Deliberately based
// on the app's own package.json dependencies rather than Nx's project graph
// (graph.dependencies doesn't include npm: edges in this workspace, and
// target commands/executors are a plugin-version-specific implementation
// detail), so it stays meaningful even as Nx/plugin internals change.
//
// Returns undefined for anything this generator doesn't recognize — that's
// not an error here. The caller treats a recognized framework's Dockerfile
// as generator-owned (always (re)written), and falls back to requiring an
// already-existing, hand-written Dockerfile for everything else.
function detectFramework(tree: Tree, app: App): Framework | undefined {
  const packageJsonPath = joinPathFragments(app.data.root, 'package.json');
  const packageJsonContent = tree.exists(packageJsonPath)
    ? tree.read(packageJsonPath, 'utf-8')
    : null;
  const packageJson = packageJsonContent ? JSON.parse(packageJsonContent) : {};
  const dependencies = {
    ...packageJson.dependencies,
    ...packageJson.devDependencies,
  };

  for (const [framework, dependencyName] of Object.entries(
    FRAMEWORK_DEPENDENCY,
  ) as [Framework, string][]) {
    if (dependencyName in dependencies) {
      return framework;
    }
  }

  return undefined;
}

// transitive closure of an app's workspace-internal dependencies, both
// explicit (detected imports, TS project references) and implicit
// (`implicitDependencies` in project.json) — Nx's own graph doesn't
// distinguish these in a way that matters here, so every edge is followed.
// npm: external packages have no node in the graph and are skipped, since
// pnpm installs those on its own from the lockfile.
function getWorkspaceDependencies(
  graph: ProjectGraph,
  projectName: string,
): { name: string; root: string }[] {
  const visited = new Set<string>([projectName]);
  const queue = [projectName];
  const dependencies: { name: string; root: string }[] = [];

  while (queue.length > 0) {
    const current = queue.shift() as string;

    for (const edge of graph.dependencies[current] ?? []) {
      if (visited.has(edge.target)) {
        continue;
      }
      visited.add(edge.target);

      const node = graph.nodes[edge.target];
      if (!node) {
        continue;
      }

      dependencies.push({ name: edge.target, root: node.data.root });
      queue.push(edge.target);
    }
  }

  return dependencies.sort((a, b) => a.name.localeCompare(b.name));
}

// step 2: generate the Dockerfile matching the app's detected framework.
// Only Next.js is implemented so far. Only called for apps detectFramework()
// actually recognized — everything else keeps its own hand-written Dockerfile.
function buildDockerfile(
  framework: Framework,
  app: App,
  dependencies: { name: string; root: string }[],
): string {
  switch (framework) {
    case 'nextjs':
      return buildNextJsDockerfile(app, dependencies);
  }
}

// assumes a Next.js app built via @nx/next: `nx build`/`nx dev` targets and a
// `.next/standalone` production output.
function buildNextJsDockerfile(
  app: App,
  dependencies: { name: string; root: string }[],
): string {
  // sorted (and deduplicated by definition, since dependencies never include
  // the app's own root) for deterministic output across regenerations
  const roots = [app.data.root, ...dependencies.map((dep) => dep.root)].sort();

  const packageJsonCopies = roots
    .map((root) => `COPY ${root}/package.json ${root}/package.json`)
    .join('\n');
  const sourceCopies = roots.map((root) => `COPY ${root} ${root}`).join('\n');

  return `# syntax=docker/dockerfile:1
${GENERATED_FILE_MARKER}
FROM node:24-alpine AS base
RUN corepack enable && corepack prepare pnpm@11.21.0 --activate
WORKDIR ${WORKSPACE_DIR}
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps
COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
${packageJsonCopies}
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \\
    pnpm install --frozen-lockfile

FROM deps AS source
COPY nx.json tsconfig.base.json ./
${sourceCopies}

FROM source AS builder
RUN --mount=type=cache,id=next-${app.name},target=${WORKSPACE_DIR}/${app.data.root}/.next/cache \\
    pnpm exec nx build ${app.name} --skip-sync

FROM source AS dev
ENV NODE_ENV=development
EXPOSE 3000
CMD ["pnpm", "exec", "nx", "dev", "${app.name}", "--skip-sync"]

FROM base AS runner
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
RUN addgroup --system --gid 1001 nodejs \\
    && adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs ${WORKSPACE_DIR}/${app.data.root}/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs ${WORKSPACE_DIR}/${app.data.root}/.next/static ./${app.data.root}/.next/static
COPY --from=builder --chown=nextjs:nodejs ${WORKSPACE_DIR}/${app.data.root}/public ./${app.data.root}/public

USER nextjs
EXPOSE 3000

CMD ["node", "${app.data.root}/server.js"]
`;
}

// relative path from a Next.js app's own directory back to the workspace
// root, for its next.config.js's `outputFileTracingRoot` — in a monorepo,
// tracing otherwise defaults to the app's own directory, silently excluding
// workspace dependencies (and pnpm-hoisted node_modules) that live outside
// it from the standalone build. Computed via workspaceRoot rather than
// assuming a fixed nesting depth, so it stays correct regardless of how
// deep the app happens to live.
function getOutputFileTracingRootExpr(appRoot: string): string {
  const relativePath = relative(join(workspaceRoot, appRoot), workspaceRoot);
  const posixPath = relativePath.split(sep).join('/');
  return `path.join(__dirname, '${posixPath}')`;
}

// locates the object literal a next.config.js actually exports, handling
// both shapes @nx/next's own template (and most hand-written configs) use:
// `module.exports = { ... }` / `export default { ... }` directly, or via an
// intermediate `const nextConfig = { ... }` binding.
function findNextConfigObject(
  sourceFile: ts.SourceFile,
): ts.ObjectLiteralExpression | undefined {
  let exported: ts.Expression | undefined;

  for (const statement of sourceFile.statements) {
    if (ts.isExportAssignment(statement)) {
      exported = statement.expression;
    } else if (
      ts.isExpressionStatement(statement) &&
      ts.isBinaryExpression(statement.expression) &&
      statement.expression.operatorToken.kind === ts.SyntaxKind.EqualsToken &&
      ts.isPropertyAccessExpression(statement.expression.left) &&
      ts.isIdentifier(statement.expression.left.expression) &&
      statement.expression.left.expression.text === 'module' &&
      statement.expression.left.name.text === 'exports'
    ) {
      exported = statement.expression.right;
    }
  }

  if (!exported) {
    return undefined;
  }
  if (ts.isObjectLiteralExpression(exported)) {
    return exported;
  }
  if (!ts.isIdentifier(exported)) {
    return undefined;
  }

  const boundName = exported.text;
  for (const statement of sourceFile.statements) {
    if (!ts.isVariableStatement(statement)) {
      continue;
    }
    for (const declaration of statement.declarationList.declarations) {
      if (
        ts.isIdentifier(declaration.name) &&
        declaration.name.text === boundName &&
        declaration.initializer &&
        ts.isObjectLiteralExpression(declaration.initializer)
      ) {
        return declaration.initializer;
      }
    }
  }

  return undefined;
}

function findNextConfigProperty(
  configObject: ts.ObjectLiteralExpression,
  name: string,
): ts.PropertyAssignment | undefined {
  for (const property of configObject.properties) {
    if (
      ts.isPropertyAssignment(property) &&
      ((ts.isIdentifier(property.name) && property.name.text === name) ||
        (ts.isStringLiteral(property.name) && property.name.text === name))
    ) {
      return property;
    }
  }
  return undefined;
}

// whether the file's own export uses ES module syntax (`export default`)
// rather than CommonJS (`module.exports = `) — determines which form a
// newly-inserted `path` import should use, to match the file's own style.
function usesEsmExport(sourceFile: ts.SourceFile): boolean {
  return sourceFile.statements.some(ts.isExportAssignment);
}

// true if the file already binds an identifier named `path` to the `path`
// module, via either `require('path')` or an ES import — needed alongside
// `outputFileTracingRoot`, which is always expressed as `path.join(...)`.
function hasPathModuleImport(sourceFile: ts.SourceFile): boolean {
  for (const statement of sourceFile.statements) {
    if (
      ts.isImportDeclaration(statement) &&
      ts.isStringLiteral(statement.moduleSpecifier) &&
      statement.moduleSpecifier.text === 'path'
    ) {
      return true;
    }
    if (!ts.isVariableStatement(statement)) {
      continue;
    }
    for (const declaration of statement.declarationList.declarations) {
      if (
        ts.isIdentifier(declaration.name) &&
        declaration.name.text === 'path' &&
        declaration.initializer &&
        ts.isCallExpression(declaration.initializer) &&
        ts.isIdentifier(declaration.initializer.expression) &&
        declaration.initializer.expression.text === 'require' &&
        declaration.initializer.arguments.length === 1 &&
        ts.isStringLiteral(declaration.initializer.arguments[0]) &&
        declaration.initializer.arguments[0].text === 'path'
      ) {
        return true;
      }
    }
  }
  return false;
}

type TextEdit = { start: number; end: number; text: string };

// overwrites the property's value if present (whatever it currently is —
// these two properties are generator-managed, unlike the rest of the file),
// or appends a new one right before the object literal's closing brace,
// preserving every other property, comment, and piece of formatting as-is.
function upsertNextConfigProperty(
  configObject: ts.ObjectLiteralExpression,
  name: string,
  valueText: string,
  edits: TextEdit[],
): void {
  const existing = findNextConfigProperty(configObject, name);
  if (existing) {
    if (existing.initializer.getText() !== valueText) {
      edits.push({
        start: existing.initializer.getStart(),
        end: existing.initializer.getEnd(),
        text: valueText,
      });
    }
    return;
  }

  const properties = configObject.properties;
  const needsLeadingComma =
    properties.length > 0 && !properties.hasTrailingComma;
  // `properties.end` (the NodeArray's own end, not the last element's)
  // already extends past an existing trailing comma when there is one —
  // inserting at the last property's own getEnd() instead would land
  // *before* that comma, leaving it orphaned between our insertion and
  // whatever edit updates that same last property's value
  const insertPos =
    properties.length > 0 ? properties.end : configObject.getStart() + 1;

  edits.push({
    start: insertPos,
    end: insertPos,
    text: `${needsLeadingComma ? ',' : ''}\n  ${name}: ${valueText},`,
  });
}

// step 3 (Next.js apps only): maintain `output` and `outputFileTracingRoot`
// in the app's own next.config.js — everything else in that file is left
// exactly as the developer wrote it. Unlike the Dockerfile, this file is
// never fully generated/overwritten: these two properties are the only
// thing this generator owns here.
function syncNextConfig(tree: Tree, app: App): void {
  const configPath = joinPathFragments(app.data.root, 'next.config.js');
  const outputFileTracingRootExpr = getOutputFileTracingRootExpr(app.data.root);

  if (!tree.exists(configPath)) {
    tree.write(
      configPath,
      `const path = require('path');

/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  outputFileTracingRoot: ${outputFileTracingRootExpr},
};

module.exports = nextConfig;
`,
    );
    return;
  }

  const content = tree.read(configPath, 'utf-8') as string;
  const sourceFile = ts.createSourceFile(
    configPath,
    content,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.JS,
  );

  const configObject = findNextConfigObject(sourceFile);
  if (!configObject) {
    throw new SyncError(
      `Could not find the exported Next.js config object in ${configPath}`,
      [
        `Expected either "module.exports = { ... }" or`,
        `"const x = { ... }; module.exports = x;" (or the "export default"`,
        `equivalent). Adjust the file to one of these shapes, or maintain`,
        `"output" and "outputFileTracingRoot" in it by hand.`,
      ],
    );
  }

  const edits: TextEdit[] = [];
  upsertNextConfigProperty(configObject, 'output', `'standalone'`, edits);
  upsertNextConfigProperty(
    configObject,
    'outputFileTracingRoot',
    outputFileTracingRootExpr,
    edits,
  );

  if (!hasPathModuleImport(sourceFile)) {
    const insertPos =
      sourceFile.statements.length > 0
        ? sourceFile.statements[0].getStart()
        : 0;
    const pathImportText = usesEsmExport(sourceFile)
      ? `import * as path from 'path';\n\n`
      : `const path = require('path');\n\n`;
    edits.push({
      start: insertPos,
      end: insertPos,
      text: pathImportText,
    });
  }

  if (edits.length === 0) {
    return;
  }

  // built by walking the edits in order against the original, untouched
  // `content` — never re-sliced against a progressively-mutated string,
  // since that breaks the moment two edits' start/end offsets coincide
  // (e.g. a value replacement ending exactly where a new property is
  // inserted right after it)
  edits.sort((a, b) => a.start - b.start);
  let newContent = '';
  let cursor = 0;
  for (const edit of edits) {
    newContent += content.slice(cursor, edit.start) + edit.text;
    cursor = edit.end;
  }
  newContent += content.slice(cursor);

  tree.write(configPath, newContent);
}

// stage name skaffold's dev-loop build targets. Generator-owned (recognized
// framework) Dockerfiles always have one by construction; a hand-written
// Dockerfile for an unrecognized framework only gets `docker.target: dev` set
// if it actually declares a stage named that — otherwise `docker build
// --target dev` would fail outright with an unknown-stage error.
const DEV_STAGE_PATTERN = /^FROM\s+\S+\s+AS\s+dev\s*$/im;

function getDevTarget(
  tree: Tree,
  app: App,
  framework: Framework | undefined,
): string | undefined {
  if (framework) {
    return 'dev';
  }

  const dockerfilePath = joinPathFragments(app.data.root, 'Dockerfile');
  const content = tree.read(dockerfilePath, 'utf-8') ?? '';
  return DEV_STAGE_PATTERN.test(content) ? 'dev' : undefined;
}

function buildArtifact(
  tree: Tree,
  app: App,
  framework: Framework | undefined,
  // workspace dependencies whose *source* is worth live-syncing too (e.g. a
  // shared lib the app imports from) — only meaningful for a recognized
  // framework's generator-owned Dockerfile, since that's the only case where
  // we know for certain each dependency's root is actually COPYed in at the
  // same paths (see buildNextJsDockerfile). Empty for a hand-written
  // Dockerfile: we have no idea how (or whether) it copies dependencies in.
  dependencies: { name: string; root: string }[],
) {
  const target = getDevTarget(tree, app, framework);

  return {
    image: app.name,
    // relative to this file's own directory (skaffold/), since this config
    // is always loaded as a `requires` module, never as the entrypoint
    context: '..',
    docker: {
      dockerfile: `${app.data.root}/Dockerfile`,
      ...(target ? { target } : {}),
    },
    sync: {
      manual: [
        { src: `${app.data.root}/src/**/*`, dest: '.' },
        { src: `${app.data.root}/public/**/*`, dest: '.' },
        ...dependencies.map((dep) => ({
          src: `${dep.root}/src/**/*`,
          dest: '.',
        })),
      ],
    },
  };
}

function buildProductionArtifact(app: App) {
  return {
    image: app.name,
    context: '..',
    docker: {
      dockerfile: `${app.data.root}/Dockerfile`,
      // no target: builds the Dockerfile's last stage (the real production build)
    },
    // no sync: nothing in a production image is watching for file changes
  };
}

function readK8sResources(tree: Tree, k8sDir: string): K8sResource[] {
  const resources: K8sResource[] = [];

  for (const file of tree.children(k8sDir)) {
    if (!isYamlFile(file)) {
      continue;
    }

    const filePath = joinPathFragments(k8sDir, file);
    const content = tree.read(filePath, 'utf-8');
    if (!content) {
      continue;
    }

    for (const doc of yaml.parseAllDocuments(content)) {
      if (doc.errors.length > 0) {
        throw new SyncError(`Failed to parse ${filePath}`, [
          ...doc.errors.map((error) => error.message),
        ]);
      }

      const resource = doc.toJSON();
      // skip empty documents, e.g. from a trailing "---"
      if (resource) {
        resources.push({ file: filePath, resource });
      }
    }
  }

  return resources;
}

function getResourceNamespaces(tree: Tree, k8sDir: string): string[] {
  return readK8sResources(tree, k8sDir)
    .map(({ resource }) => resource.metadata?.namespace)
    .filter((namespace): namespace is string => Boolean(namespace));
}

function getAppNamespace(tree: Tree, k8sDir: string, appName: string): string {
  const namespaces = new Set(getResourceNamespaces(tree, k8sDir));

  if (namespaces.size > 1) {
    throw new SyncError(`App "${appName}" declares more than one namespace`, [
      `Found namespaces: ${[...namespaces].join(', ')} across resources in ${k8sDir}.`,
      `Each app must target exactly one namespace across all of its k8s manifests.`,
    ]);
  }

  const namespace =
    namespaces.size === 1 ? [...namespaces][0] : DEFAULT_NAMESPACE;

  if (namespace !== DEFAULT_NAMESPACE && !NAMESPACE_PATTERN.test(namespace)) {
    throw new SyncError(
      `App "${appName}" declares an invalid namespace "${namespace}"`,
      [
        `Kubernetes namespace names must be lowercase alphanumeric characters or '-',`,
        `must start and end with an alphanumeric character, and be at most 63 characters long.`,
        `Found in ${k8sDir}.`,
      ],
    );
  }

  if (RESERVED_NAMESPACES.has(namespace)) {
    throw new SyncError(
      `App "${appName}" cannot use the reserved namespace "${namespace}"`,
      [
        `"${namespace}" is reserved for the hand-maintained skaffold/${namespace}.yaml.`,
        `Choose a different namespace for this app.`,
      ],
    );
  }

  return namespace;
}

function getServicePortForwards(tree: Tree, k8sDir: string, namespace: string) {
  const portForwards: {
    resourceType: string;
    resourceName: string;
    namespace: string;
    port: number;
    localPort: number;
  }[] = [];

  for (const { file, resource } of readK8sResources(tree, k8sDir)) {
    if (resource.kind !== 'Service') {
      continue;
    }

    const resourceName = resource.metadata?.name;
    if (!resourceName) {
      throw new SyncError(`Service in ${file} is missing metadata.name`, [
        `Every Service manifest must declare metadata.name so it can be port-forwarded.`,
      ]);
    }

    for (const port of resource.spec?.ports ?? []) {
      if (typeof port.port !== 'number') {
        throw new SyncError(
          `Service "${resourceName}" in ${file} has a port entry without a numeric "port"`,
          [`Found: ${JSON.stringify(port)}`],
        );
      }

      portForwards.push({
        resourceType: 'service',
        resourceName,
        namespace,
        port: port.port,
        localPort: port.port,
      });
    }
  }

  return portForwards;
}

function buildNamespaceManifest(namespace: string) {
  if (namespace === DEFAULT_NAMESPACE) {
    // the "default" namespace always exists; every other namespace referenced
    // by deploy.kubectl.defaultNamespace must be created before it's deployed into
    return undefined;
  }

  return {
    path: `${namespace}-namespace.yaml`,
    content: yaml.stringify({
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: { name: namespace },
    }),
  };
}

function buildNamespaceConfig(
  tree: Tree,
  namespace: string,
  apps: App[],
  frameworks: Map<string, Framework | undefined>,
  dependenciesByApp: Map<string, { name: string; root: string }[]>,
) {
  const portForward = apps.flatMap((app) =>
    getServicePortForwards(
      tree,
      joinPathFragments(app.data.root, 'k8s'),
      namespace,
    ),
  );

  const namespaceManifestPath =
    namespace !== DEFAULT_NAMESPACE ? `${namespace}-namespace.yaml` : undefined;

  return {
    apiVersion: 'skaffold/v4beta13',
    kind: 'Config',
    metadata: {
      name: `dx-stack-${namespace}`,
    },
    build: {
      artifacts: apps.map((app) =>
        buildArtifact(
          tree,
          app,
          frameworks.get(app.name),
          dependenciesByApp.get(app.name) ?? [],
        ),
      ),
      local: {
        useDockerCLI: true,
        useBuildkit: true,
      },
    },
    manifests: {
      // relative to this file's own directory (skaffold/), since this config
      // is always loaded as a `requires` module, never as the entrypoint
      rawYaml: [
        ...(namespaceManifestPath ? [namespaceManifestPath] : []),
        ...apps.map((app) => `../${app.data.root}/k8s/*.yaml`),
      ],
    },
    deploy: {
      kubectl: {
        defaultNamespace: namespace,
        flags: {
          global: ['--context=minikube'],
        },
      },
    },
    ...(portForward.length > 0 ? { portForward } : {}),
    // activated with `-p production`; skaffold propagates an activated
    // profile name to every required config that defines a matching one, so
    // `-p production` on the top-level skaffold.yaml reaches this file too
    profiles: [
      {
        name: 'production',
        build: {
          artifacts: apps.map((app) => buildProductionArtifact(app)),
          local: {
            useDockerCLI: true,
            useBuildkit: true,
          },
        },
      },
    ],
  };
}

export async function syncGenerator(tree: Tree): Promise<SyncGeneratorResult> {
  const graph = await createProjectGraphAsync();

  const allAppNodes: App[] = Object.values(graph.nodes).filter(
    (node) => node.type === 'app',
  );

  const k8sQualifyingApps = allAppNodes.filter((node) => {
    const k8sDir = joinPathFragments(node.data.root, 'k8s');
    return tree.exists(k8sDir) && hasYamlFiles(tree, k8sDir);
  });

  const frameworks = new Map<string, Framework | undefined>(
    k8sQualifyingApps.map((app) => [app.name, detectFramework(tree, app)]),
  );

  const apps: App[] = k8sQualifyingApps
    .filter((app) => {
      // a recognized framework's Dockerfile is generator-owned — it always
      // qualifies, and gets (re)written below regardless of what's already
      // there. Anything else only qualifies if a Dockerfile already exists:
      // this generator doesn't know how to write one for an unrecognized
      // framework, and won't silently skip building the app either — the
      // existing Dockerfile is what makes that app buildable at all.
      return (
        frameworks.get(app.name) !== undefined ||
        tree.exists(joinPathFragments(app.data.root, 'Dockerfile'))
      );
    })
    // deterministic order so regenerating with no actual changes produces
    // byte-identical output, regardless of project graph iteration order
    .sort((a, b) => a.name.localeCompare(b.name));

  for (const app of apps) {
    assertValidImageName(app.name);
  }

  const appsByNamespace = new Map<string, App[]>();
  for (const app of apps) {
    const namespace = getAppNamespace(
      tree,
      joinPathFragments(app.data.root, 'k8s'),
      app.name,
    );
    appsByNamespace.set(namespace, [
      ...(appsByNamespace.get(namespace) ?? []),
      app,
    ]);
  }

  const namespaces = [...appsByNamespace.keys()].sort();

  const expectedSkaffoldFiles = new Set<string>(['skaffold.yaml']);
  for (const namespace of namespaces) {
    expectedSkaffoldFiles.add(`${namespace}.yaml`);
    if (namespace !== DEFAULT_NAMESPACE) {
      expectedSkaffoldFiles.add(`${namespace}-namespace.yaml`);
    }
  }

  // remove generated skaffold/ files left behind by a previous run that are
  // no longer needed (e.g. an app switched namespaces); never touches
  // hand-authored files, since only files carrying our own marker are eligible
  for (const file of tree.children('skaffold')) {
    if (expectedSkaffoldFiles.has(file) || file === 'infra.yaml') {
      continue;
    }
    if (!isYamlFile(file)) {
      continue;
    }

    const filePath = `skaffold/${file}`;
    const content = tree.read(filePath, 'utf-8');
    if (content?.includes(GENERATED_FILE_MARKER)) {
      tree.delete(filePath);
    }
  }

  // same for a project's own generated Dockerfile, if it stopped qualifying
  // (e.g. its k8s/ folder was removed)
  const qualifyingRoots = new Set(apps.map((app) => app.data.root));
  for (const node of allAppNodes) {
    if (qualifyingRoots.has(node.data.root)) {
      continue;
    }

    const dockerfilePath = joinPathFragments(node.data.root, 'Dockerfile');
    const content = tree.exists(dockerfilePath)
      ? tree.read(dockerfilePath, 'utf-8')
      : null;
    if (content?.includes(GENERATED_FILE_MARKER)) {
      tree.delete(dockerfilePath);
    }
  }

  const written = new Set<string>();
  function write(path: string, content: string) {
    if (written.has(path)) {
      throw new SyncError(
        `Generated file "${path}" would be written more than once`,
        [`Two different namespaces produced a colliding generated file name.`],
      );
    }
    written.add(path);
    tree.write(path, content);
  }

  // only computed for a recognized framework: that's the only case where
  // buildDockerfile() actually COPYs each dependency's root in, so it's the
  // only case where syncing that same root's source back out (buildArtifact)
  // means anything
  const dependenciesByApp = new Map<string, { name: string; root: string }[]>(
    apps
      .filter((app) => frameworks.get(app.name))
      .map((app) => [app.name, getWorkspaceDependencies(graph, app.name)]),
  );

  for (const app of apps) {
    const framework = frameworks.get(app.name);
    if (!framework) {
      // unrecognized framework: qualification above already confirmed a
      // hand-written Dockerfile exists here, so it's left untouched
      continue;
    }

    write(
      joinPathFragments(app.data.root, 'Dockerfile'),
      buildDockerfile(framework, app, dependenciesByApp.get(app.name) ?? []),
    );

    if (framework === 'nextjs') {
      syncNextConfig(tree, app);
    }
  }

  for (const namespace of namespaces) {
    const namespaceApps = appsByNamespace.get(namespace) ?? [];

    const namespaceManifest = buildNamespaceManifest(namespace);
    if (namespaceManifest) {
      write(
        `skaffold/${namespaceManifest.path}`,
        GENERATED_FILE_MARKER + namespaceManifest.content,
      );
    }

    write(
      `skaffold/${namespace}.yaml`,
      GENERATED_FILE_MARKER +
        yaml.stringify(
          buildNamespaceConfig(
            tree,
            namespace,
            namespaceApps,
            frameworks,
            dependenciesByApp,
          ),
        ),
    );
  }

  write(
    'skaffold/skaffold.yaml',
    GENERATED_FILE_MARKER +
      yaml.stringify({
        apiVersion: 'skaffold/v4beta13',
        kind: 'Config',
        metadata: {
          name: 'dx-stack',
        },
        ...(namespaces.length > 0
          ? {
              requires: namespaces.map((namespace) => ({
                path: `${namespace}.yaml`,
              })),
            }
          : {}),
      }),
  );

  return {
    outOfSyncMessage: 'skaffold/skaffold.yaml is missing or not in sync',
  };
}

export default syncGenerator;
