import type { Tree } from '@nx/devkit';

// present (anywhere) in every generated file so stale ones (e.g. a namespace
// that no app references anymore) can be safely identified and pruned later,
// without ever touching a file a developer authored by hand. Exported so
// implementing adapters can embed it in their own generated Dockerfiles too.
export const GENERATED_FILE_MARKER =
  '# Generated by @dx-stack/skaffold:sync. Do not edit directly — run `nx sync` to regenerate.\n';

// a single workspace project, flattened off the raw Nx project-graph node
// shape (which nests the root under `.data.root`) — adapters are separate
// packages that shouldn't need to know anything about Nx's ProjectGraph.
export interface WorkspaceProject {
  readonly name: string;
  readonly root: string;
}

export type WorkspaceApp = WorkspaceProject;
export type WorkspaceDependency = WorkspaceProject;

export interface SyncPath {
  src: string;
  dest: string;
}

/**
 * The contract a framework-specific package (`@dx-stack/next-skaffold`, a
 * hypothetical future `@dx-stack/angular-skaffold`, ...) implements so
 * `@dx-stack/skaffold`'s sync generator can generate that framework's apps.
 *
 * `@dx-stack/skaffold` owns everything framework-agnostic: app discovery
 * (scanning for `k8s/*.yaml`), namespace assignment/validation,
 * port-forward derivation, skaffold.yaml/production-profile assembly,
 * generated-file marker + pruning, image-name validation, the app's own
 * default `sync.manual` paths (`src/**\/*` unconditionally, `public/**\/*`
 * too if the app has one — both regardless of framework), and the fallback
 * for an app no adapter recognizes but which already has a hand-written
 * Dockerfile. Everything below is
 * what's left: turning a recognized app into a Dockerfile + framework
 * config, plus any *additional* sync paths its dependencies need.
 */
export interface FrameworkAdapter {
  /** Used only in error messages (e.g. two adapters activating for one app). */
  readonly name: string;

  /**
   * Whether this adapter recognizes `app` as built with its framework —
   * typically via the app's own `package.json` dependencies. Only ever
   * called for apps that already qualify as skaffold candidates (a
   * non-empty `k8s/` folder) — never for every app in the workspace.
   *
   * If no adapter activates for an app, it's still a candidate as long as
   * `<root>/Dockerfile` already exists by hand. If more than one adapter
   * activates for the same app, `nx sync` fails with a clear error naming
   * every adapter involved — not resolved automatically.
   */
  activates(tree: Tree, app: WorkspaceApp): boolean;

  /**
   * Builds the full contents of the app's `Dockerfile` — fully generated
   * and owned by this adapter; (re)written on every run.
   *
   * MUST declare a build stage named exactly `dev`: the core
   * unconditionally sets `docker.target: 'dev'` for any app whose
   * Dockerfile an adapter built (never delegated per-adapter) — this is a
   * hard requirement of the contract, not an implementation detail of any
   * one adapter's template.
   *
   * MUST embed `GENERATED_FILE_MARKER` (exported above) somewhere in the
   * returned content (anywhere after a required leading directive, e.g.
   * Docker's `# syntax=`) — that's what lets core safely prune it later if
   * the app stops qualifying.
   *
   * Pure function of `app`/`dependencies` — never touches the `Tree`, so
   * it's trivial to unit test in isolation.
   */
  buildDockerfile(
    app: WorkspaceApp,
    dependencies: WorkspaceDependency[],
  ): string;

  /**
   * Extra source paths worth live-syncing (`sync.manual`) beyond the
   * app's own default paths — typically the same `src/**\/*`-style path
   * for each workspace dependency this adapter's Dockerfile actually
   * `COPY`s in. Only called for dependencies of an app this same adapter
   * activated for (dependencies aren't computed at all otherwise).
   * Pure function — same rationale as `buildDockerfile`.
   */
  getDependencySyncPaths(dependencies: WorkspaceDependency[]): SyncPath[];

  /**
   * Optional: maintain framework-specific config file(s) the Dockerfile
   * build depends on (e.g. Next.js's `output`/`outputFileTracingRoot` in
   * `next.config.js`). Unlike the Dockerfile, typically NOT a fully
   * generated/overwritten file — just specific properties within an
   * otherwise hand-maintained file — and never marker-tracked/pruned.
   * Only called for apps this adapter activated for.
   */
  syncFrameworkConfig?(tree: Tree, app: WorkspaceApp): void;
}

export type SkaffoldAdapters = readonly FrameworkAdapter[];
