apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: apps
  labels:
    app: example
spec:
  type: ClusterIP
  selector:
    app: example
  ports:
    - port: 3000
      targetPort: 3000
