apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: dx-stack-infra
manifests:
  rawYaml:
    - skaffold/infra/*.yaml
deploy:
  helm:
  kubectl:
    flags:
      global:
        - --context=minikube